#!/usr/bin/env python3
import json, os, urllib.request
from datetime import date, timedelta
from html import escape

TOKEN = os.environ["GITHUB_TOKEN"]
ENDPOINT = "https://api.github.com/graphql"

QUERY = """
query($from: DateTime!, $to: DateTime!) {
  viewer {
    followers { totalCount }
    repositories(ownerAffiliations: OWNER, privacy: PUBLIC, first: 100, orderBy: {field: UPDATED_AT, direction: DESC}) {
      totalCount
      nodes {
        languages(first: 10, orderBy: {field: SIZE, direction: DESC}) {
          edges { size node { name color } }
        }
      }
    }
    contributionsCollection(from: $from, to: $to) {
      totalCommitContributions
      totalIssueContributions
      totalPullRequestContributions
      totalPullRequestReviewContributions
      contributionCalendar {
        totalContributions
        weeks { contributionDays { date contributionCount } }
      }
    }
  }
}
"""

today = date.today()
from_date = today - timedelta(days=365)
body = json.dumps({
    "query": QUERY,
    "variables": {
        "from": f"{from_date.isoformat()}T00:00:00Z",
        "to": f"{today.isoformat()}T23:59:59Z",
    }
}).encode()

request = urllib.request.Request(
    ENDPOINT,
    data=body,
    headers={
        "Authorization": f"bearer {TOKEN}",
        "Content-Type": "application/json",
        "User-Agent": "Mahdiyar185-profile-assets",
    },
    method="POST",
)

with urllib.request.urlopen(request, timeout=30) as response:
    payload = json.load(response)

if payload.get("errors"):
    raise SystemExit(json.dumps(payload["errors"]))

viewer = payload["data"]["viewer"]
cc = viewer["contributionsCollection"]
repos = viewer["repositories"]

days = []
for week in cc["contributionCalendar"]["weeks"]:
    days.extend(week["contributionDays"])
days.sort(key=lambda x: x["date"])

current = 0
for item in reversed(days):
    if item["contributionCount"] > 0:
        current += 1
    else:
        break

longest = 0
run = 0
for item in days:
    if item["contributionCount"] > 0:
        run += 1
        longest = max(longest, run)
    else:
        run = 0

active_days = sum(1 for item in days if item["contributionCount"] > 0)

language_sizes = {}
language_colors = {}
for repo in repos["nodes"]:
    for edge in repo["languages"]["edges"]:
        name = edge["node"]["name"]
        language_sizes[name] = language_sizes.get(name, 0) + edge["size"]
        language_colors[name] = edge["node"].get("color") or "#38BDF8"

top_languages = sorted(language_sizes.items(), key=lambda pair: pair[1], reverse=True)[:5]
total_language_size = sum(language_sizes.values()) or 1

def shell(title, height=250):
    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="920" height="{height}" viewBox="0 0 920 {height}" role="img" aria-label="{escape(title)}">',
        '<defs>',
        '<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="#07101F"/><stop offset="55%" stop-color="#0B1730"/><stop offset="100%" stop-color="#180C2F"/></linearGradient>',
        '<linearGradient id="line" x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stop-color="#22D3EE"/><stop offset="55%" stop-color="#6366F1"/><stop offset="100%" stop-color="#D946EF"/></linearGradient>',
        '</defs>',
        f'<rect width="920" height="{height}" rx="22" fill="url(#bg)" stroke="#24365A"/>',
        '<circle cx="815" cy="36" r="85" fill="#7C3AED" opacity=".08"/>',
        '<circle cx="710" cy="220" r="90" fill="#06B6D4" opacity=".06"/>',
        f'<text x="34" y="42" fill="#F8FAFC" font-family="Inter,Segoe UI,Arial,sans-serif" font-size="21" font-weight="700">{escape(title)}</text>',
        '<path d="M34 64 H886" stroke="url(#line)" opacity=".55"/>',
    ]

def t(x, y, value, size=13, color="#CBD5E1", weight=600):
    return f'<text x="{x}" y="{y}" fill="{color}" font-family="Inter,Segoe UI,Arial,sans-serif" font-size="{size}" font-weight="{weight}">{escape(str(value))}</text>'

# Stats
s = shell("GitHub Activity")
metrics = [
    ("PUBLIC REPOS", repos["totalCount"]),
    ("FOLLOWERS", viewer["followers"]["totalCount"]),
    ("COMMITS · 1Y", cc["totalCommitContributions"]),
    ("PULL REQUESTS", cc["totalPullRequestContributions"]),
    ("ISSUES", cc["totalIssueContributions"]),
    ("REVIEWS", cc["totalPullRequestReviewContributions"]),
]
for (label, value), (x, y) in zip(metrics, [(34, 110), (330, 110), (626, 110), (34, 188), (330, 188), (626, 188)]):
    s.append(t(x, y-18, label, 11, "#7DD3FC", 700))
    s.append(t(x, y+12, value, 28, "#F8FAFC", 800))
    s.append(f'<rect x="{x}" y="{y+26}" width="230" height="3" rx="2" fill="url(#line)" opacity=".75"/>')
s.append(t(34, 238, "Live data generated by GitHub Actions — no external stats-card service.", 11, "#64748B", 500))
s.append("</svg>")
open("assets/github-stats.svg", "w", encoding="utf-8").write("\\n".join(s))

# Contribution activity
a = shell("Contribution Activity")
total = cc["contributionCalendar"]["totalContributions"]
a += [
    t(34, 95, f"{total} contributions in the last year", 16, "#E2E8F0", 700),
    t(34, 124, f"Current streak  {current} days", 13, "#7DD3FC", 700),
    t(220, 124, f"Longest streak  {longest} days", 13, "#C4B5FD", 700),
    t(405, 124, f"Active days  {active_days}", 13, "#F0ABFC", 700),
]
recent = days[-182:]
cell, gap = 11, 3
start_x, start_y = 34, 146
for i, item in enumerate(recent):
    col, row = i % 26, i // 26
    x, y = start_x + col*(cell+gap), start_y + row*(cell+gap)
    count = item["contributionCount"]
    opacity = 0.12 if count == 0 else min(0.95, 0.28 + count*0.10)
    fill = "#38BDF8" if count else "#17233D"
    a.append(f'<rect x="{x}" y="{y}" width="{cell}" height="{cell}" rx="3" fill="{fill}" opacity="{opacity:.2f}"/>')
a += [
    t(405, 164, "Recent contribution signal", 11, "#94A3B8", 700),
    t(405, 188, "Synced from your GitHub contribution calendar.", 11, "#64748B", 500),
    t(405, 212, "The native GitHub contribution graph remains", 11, "#64748B", 500),
    t(405, 230, "the source of truth on your profile.", 11, "#64748B", 500),
    "</svg>",
]
open("assets/github-activity.svg", "w", encoding="utf-8").write("\\n".join(a))

# Languages
l = shell("Top Languages", 205)
bar_x, bar_y, bar_w, bar_h = 34, 91, 500, 16
cursor = bar_x
for name, size in top_languages:
    width = max(18, bar_w * size / total_language_size)
    l.append(f'<rect x="{cursor:.1f}" y="{bar_y}" width="{width:.1f}" height="{bar_h}" fill="{language_colors[name]}" opacity=".9"/>')
    cursor += width
for idx, (name, size) in enumerate(top_languages):
    y = 140 + idx*22
    pct = size / total_language_size * 100
    l.append(f'<circle cx="40" cy="{y-5}" r="5" fill="{language_colors[name]}"/>')
    l.append(t(54, y, f"{name}  ·  {pct:.1f}%", 12, "#CBD5E1", 600))
l.append("</svg>")
open("assets/github-languages.svg", "w", encoding="utf-8").write("\\n".join(l))
